version: '3.8'

services:
  prod_app:
    image: node:20
    container_name: prod_app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=prd
    volumes:
      - .:/app
      - /app/node_modules

  dev_app:
    image: node:20
    container_name: dev_app
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=dev
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo:4.4
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf.template
    environment:
      - app_env=prod_app:3000

volumes:
  mongo-data:
  redis-data:
