# docker-compose.yaml
version: '3.3'
services:
  app:
    image: ${DOCKER_HUB_USERNAME}/node_app:${DOCKER_TAG:-dev}
    container_name: ${CONTAINER_NAME:-node_app}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - MONGODB_URL=mongodb://mongodb:27017/${CONTAINER_NAME:-node_app}
    ports:
      - "${APP_PORT:-4000}:4000"
    depends_on:
      - mongodb
      - redis
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: ${CONTAINER_NAME:-node_app}_mongodb
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: ${CONTAINER_NAME:-node_app}_redis
    restart: unless-stopped

volumes:
  mongodb_data:
    driver: local
