version: '3.8'

services:
  prod_app:
    image: ${DOCKER_HUB_USERNAME}/app:${DOCKER_TAG}
    container_name: prod_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=prod
      - APP_ENV=prod
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - my-network

  dev_app:
    image: ${DOCKER_HUB_USERNAME}/app:${DOCKER_TAG}
    container_name: dev_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=dev
      - APP_ENV=dev
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - my-network

  mongo:
    image: mongo:4.4
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - my-network

  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - my-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - APP_ENV=${APP_ENV}
    depends_on:
      - prod_app
      - dev_app
    networks:
      - my-network

volumes:
  mongo-data:
  redis-data:
  
networks:
  my-network:
    driver: bridge