version: '3.8'

services:
  prod_app:
    image: node:20
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      MONGO_URL: mongodb://mongo:27017/prod_db
      REDIS_URL: redis://redis:6379
    networks:
      - app-network

  dev_app:
    image: node:20
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      MONGO_URL: mongodb://mongo:27017/dev_db
      REDIS_URL: redis://redis:6379
    networks:
      - app-network

  mongo:
    image: mongo:4.4
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

  redis:
    image: redis:6
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    environment:
      APP_ENV: ${APP_ENV}
    depends_on:
      - prod_app
      - dev_app
    networks:
      - app-network

volumes:
  mongo-data:
  redis-data:

networks:
  app-network:
    driver: bridge
