name: Deploy to Docker

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set environment variables based on branch
      id: vars
      run: |
        if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
          echo "BRANCH=main" >> $GITHUB_ENV
          echo "ENV_FILE=.env.prod" >> $GITHUB_ENV
          echo "REMOTE_DIR=prod" >> $GITHUB_ENV
        elif [[ "${GITHUB_REF}" == "refs/heads/dev" ]]; then
          echo "BRANCH=dev" >> $GITHUB_ENV
          echo "ENV_FILE=.env.dev" >> $GITHUB_ENV
          echo "REMOTE_DIR=dev" >> $GITHUB_ENV
        fi

    - name: Build and push Docker images
      run: |
        docker-compose --env-file ${{ env.ENV_FILE }} build
        docker-compose --env-file ${{ env.ENV_FILE }} push

    - name: Deploy to server
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-avz --delete"
      with:
        remote_dir: ${{ env.REMOTE_DIR }}
        local_dir: .
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}

    - name: Start services on server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "cd ${{ env.REMOTE_DIR }} && docker-compose --env-file ${{ env.ENV_FILE }} up -d"
