name: Deploy to Linode and Docker Hub

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Linode CLI
        run: pip install linode-cli
      
      - name: Verify Linode CLI Installation
        run: linode-cli --version
      
      - name: Configure Linode CLI
        env:
          LINODE_CLI_TOKEN: ${{ secrets.LINODE_CLI_TOKEN }}
        run: |
          export LINODE_CLI_TOKEN
          linode-cli --no-defaults linodes list
          
      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.LINODE_SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.LINODE_INSTANCE_IP }} >> ~/.ssh/known_hosts

      - name: Set Environment Variables
        run: |
          echo "APP_DIR=/root/node_app" >> $GITHUB_ENV
          echo "COMPOSE_FILE=docker-compose.yaml" >> $GITHUB_ENV
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "APP_ENV=prod" >> $GITHUB_ENV
            echo "APP_SERVICE=prod_app" >> $GITHUB_ENV
            echo "DOCKER_TAG=prod" >> $GITHUB_ENV
          else
            echo "APP_ENV=dev" >> $GITHUB_ENV
            echo "APP_SERVICE=dev_app" >> $GITHUB_ENV
            echo "DOCKER_TAG=dev" >> $GITHUB_ENV
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        run: |
          docker build -t $DOCKER_HUB_USERNAME/app:${{ env.DOCKER_TAG }} .
          docker push $DOCKER_HUB_USERNAME/app:${{ env.DOCKER_TAG }}

      - name: Verify Docker Hub Push
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        run: |
          MANIFEST=$(docker manifest inspect $DOCKER_HUB_USERNAME/app:${{ env.DOCKER_TAG }})
          if [ $? -eq 0 ]; then
            echo "Image successfully pushed and verified on Docker Hub"
          else
            echo "Failed to verify image on Docker Hub"
            exit 1
          fi

      - name: Deploy to Linode
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true)
        env:
          LINODE_INSTANCE_IP: ${{ secrets.LINODE_INSTANCE_IP }}
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        run: |
          ssh root@$LINODE_INSTANCE_IP "
            export DOCKER_HUB_USERNAME=$DOCKER_HUB_USERNAME
            export DOCKER_TAG=${{ env.DOCKER_TAG }}
            export APP_SERVICE=${{ env.APP_SERVICE }}
            # 確保目標目錄存在
            mkdir -p ${{ env.APP_DIR }}

            # 檢查是否已經存在 Git 倉庫
            if [ -d ${{ env.APP_DIR }}/.git ]; then
              # 如果存在，更新現有倉庫
              cd ${{ env.APP_DIR }}
              git fetch --all
              git checkout ${{ github.ref_name }}
              git reset --hard origin/${{ github.ref_name }}
              git clean -fd
            else
              # 如果不存在，克隆倉庫
              git clone --branch ${{ github.ref_name }} https://github.com/${{ github.repository }}.git ${{ env.APP_DIR }}
              cd ${{ env.APP_DIR }}
            fi

            # 檢查並創建 .env 文件（如果不存在）
            if [ ! -f .env.${{ env.APP_ENV }} ]; then
              cp .env.${{ env.APP_ENV }}_temp .env.${{ env.APP_ENV }}
            fi

            # 拉取最新的 Docker 映像
            docker-compose -f ${{ env.COMPOSE_FILE }} pull

            # 停止舊的容器
            docker-compose -f ${{ env.COMPOSE_FILE }} down --remove-orphans

            # 啟動新的容器
            docker-compose --env-file .env.${{ env.APP_ENV }} -f ${{ env.COMPOSE_FILE }} up -d --build ${{ env.APP_SERVICE }} mongo redis nginx
          "

      - name: Verify Deployment
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true)
        env:
          LINODE_INSTANCE_IP: ${{ secrets.LINODE_INSTANCE_IP }}
        run: |
          ssh root@$LINODE_INSTANCE_IP "
            cd ${{ env.APP_DIR }} &&
            docker ps &&
            docker-compose -f ${{ env.COMPOSE_FILE }} logs --tail=50 ${{ env.APP_SERVICE }} nginx
          "